server:
  port: 8080
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: libill
    password: lb0016512346*
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: true
#  freemarker:
#    content-type: text/html
logging:
  level:
    org.springframework.security: debug
    com.daqsoft: debug